pipeline {
    agent any

    // Add a tool configuration here...
    tools {
      maven 'maven-3.9.12'
    }

    environment {
        PROJECT_DIRECTORY = "ch4_artifacts_and_testing/04_05_challenge_create_artifacts_reports"
    }

    stages {
        stage('Source') {
            steps {
                git branch: 'main',
                    changelog: false,
                    poll: false,
                    url: 'https://github.com/LinkedInLearning/intermediate-jenkins-3978673.git'
            }
        }
        stage('Clean') {
            steps {
                dir("${env.WORKSPACE}/${env.PROJECT_DIRECTORY}"){
                    echo "Cleaning the workspace..."
                    sh 'mvn clean'
                }
            }
        }
        stage('Test') {
            steps {
                dir("${env.WORKSPACE}/${env.PROJECT_DIRECTORY}"){
                    echo "Running tests..."
                    sh 'mvn test'
                }
            }
        }
        stage('Package') {
            steps {
                dir("${env.WORKSPACE}/${env.PROJECT_DIRECTORY}"){
                    echo "Creating the JAR file..."
                    sh 'mvn package -DskipTests'
                }
            }
        }
    }
    post {
        always {
            junit allowEmptyResults: true,
                testResults: '**/TEST-com.learningjenkins.AppTest.xml'

            archiveArtifacts allowEmptyArchive: true,
                artifacts: '**/hello-1.0-SNAPSHOT.jar'
        }
    }
}
