pipeline {
  agent {
    dockerContainer 'maven:3.9.12-eclipse-temurin-25'
  }

  environment {
    MVN_REPO = "${WORKSPACE}/.m2/repository"
    MVN      = "mvn -B -e -Dmaven.repo.local=${WORKSPACE}/.m2/repository"
  }

  options {
    buildDiscarder(logRotator(daysToKeepStr: '10', numToKeepStr: '10'))
    timeout(time: 1, unit: 'HOURS')
    timestamps()
  }


  stages {
    stage('Build') {
      steps {
        // Source...
        sh 'java -version'
        sh 'mvn -version'
        git branch: 'master',
            url: 'https://github.com/jenkins-docs/simple-java-maven-app.git'

        // Test...
        sh 'mkdir -p ${MVN_REPO}'
        sh '${MVN} test'

        // Package...
        sh '${MVN} -DskipTests package'

        // Archive...
        archiveArtifacts artifacts: 'target/*.jar',
            fingerprint: true,
            allowEmptyArchive: true
      }
    }
  }
}
