pipeline {
    agent { label 'linux-node' }
    tools {
      maven 'maven-3.9.11'
    }
    stages {
        stage('Source') {
            steps {
                sh 'mvn --version'
                sh 'git --version'
                git branch: 'feature/chapter3',
                    url: 'https://github.com/LinkedInLearning/intermediate-jenkins-3978673.git',
                    credentialsId: '8d409789-65c9-4eb1-9d17-4c284d7532fc'
            }
        }
        stage('Clean') {
            steps {
                dir("${env.WORKSPACE}/ch3_agents_and_distributed_builds/03_02_add_an_ssh_agent_to_jenkins"){
                    sh 'mvn clean'
                }
            }
        }
        stage('Test') {
            steps {
                dir("${env.WORKSPACE}/ch3_agents_and_distributed_builds/03_02_add_an_ssh_agent_to_jenkins"){
                    sh 'mvn test'
                }
            }
        }
        stage('Package') {
            steps {
                dir("${env.WORKSPACE}/ch3_agents_and_distributed_builds/03_02_add_an_ssh_agent_to_jenkins"){
                    sh 'mvn package -DskipTests'
                }
            }
        }
    }
}
